# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop
- pybind

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'v7 | vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        v7 | vcpkg | "$(Agent.OS)"
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: PowerShell@2
    displayName: "Installing dependencies + making build files"
    inputs:
     filePath: 'build-deps.ps1'
     workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: MSBuild@1
    displayName: "Compiling project"
    inputs:
      solution: 'build/INSTALL.vcxproj'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Debug'
      maximumCpuCount: true
      createLogFile: true
  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'