# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop
- pybind

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'v8 | vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        v8 | vcpkg | "$(Agent.OS)"
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: PowerShell@2
    displayName: "Installing dependencies + Making build files"
    inputs:
     filePath: 'build-deps.ps1'
     workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: MSBuild@1
    displayName: "Compiling project"
    inputs:
      solution: 'INSTALL.vcxproj'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Debug'
      maximumCpuCount: true
      createLogFile: true

  - task: CopyFiles@2
    displayName: "Copying DLLs to root drop"
    inputs:
      SourceFolder: 'C:/Program Files (x86)/Warspite/Warspite/Debug'
      Contents: '**'
      TargetFolder: 'C:/Program Files (x86)/Warspite/Warspite'

  - task: DeleteFiles@1
    displayName: "Deleting duplicate DLLs"
    inputs:
      SourceFolder: 'C:/Program Files (x86)/Warspite/Warspite/Debug'
      Contents: '**'
      RemoveSourceFolder: true'

  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: 'C:/Program Files (x86)/Warspite/'
      ArtifactName: 'drop'
      publishLocation: 'Container'