# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- last-iteration

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg\'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: CmdLine@2
    condition: ne(variables.VCPKG_CACHE_RESTORED, 'true')
    displayName: Bootstrapping vcpkg
    inputs:
      script: |
        cd %VCPKG_INSTALLATION_ROOT%
        bootstrap-vcpkg.bat -disableMetrics
        
  - script: C:\vcpkg\vcpkg.exe install sdl2 sdl2-image rapidjson --triplet x64-windows
    condition: ne(variables.VCPKG_CACHE_RESTORED, 'true')
    displayName: "Installing SDL2 and SDL2-image"

  - script: mkdir build
    displayName: "Making build folder"
  - task: CMake@1
    displayName: "Generating build files"
    inputs:
        cmakeArgs: '-DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE="Debug" -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_INSTALL_PREFIX=$(System.DefaultWorkingDirectory) ..'
  - task: PythonScript@0
    displayName: "Generating build metadata"
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(System.DefaultWorkingDirectory)\Engine\GitVersion.py'
  - task: MSBuild@1
    displayName: "Compiling project"
    inputs:
      solution: 'build/INSTALL.vcxproj'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Debug'
      createLogFile: true

  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/Warspite/'
      ArtifactName: 'drop'
      publishLocation: 'Container'