# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'v5 | vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        v5 | vcpkg | "$(Agent.OS)"
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg\'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: CmdLine@2
    condition: ne(variables.VCPKG_CACHE_RESTORED, 'true')
    displayName: Bootstrapping vcpkg
    inputs:
      script: |
        cd %VCPKG_INSTALLATION_ROOT%
        bootstrap-vcpkg.bat -disableMetrics
        
  - script: C:\vcpkg\vcpkg.exe install sdl2 sdl2-image[libjpeg-turbo,libwebp,tiff] openal-soft rapidjson zlib --triplet x64-windows
    condition: ne(variables.VCPKG_CACHE_RESTORED, 'true')
    displayName: "Installing dependencies"
    
  - task: PythonScript@0
    displayName: "Generating build metadata"
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(System.DefaultWorkingDirectory)\Engine\GitVersion.py'
      
  - task: run-cmake@0
    inputs:
      cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
      cmakeToolchainPath: 'C:\vcpkg\scripts\buildsystems\vcpkg.cmake'
      useVcpkgToolchainFile: true
      vcpkgTriplet: 'x64-windows'
      cmakeGenerator: 'Ninja'

  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/Warspite/'
      ArtifactName: 'drop'
      publishLocation: 'Container'