# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop

jobs:
- job: "Windows_x64"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'v8 | vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        v8 | vcpkg | "$(Agent.OS)"
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: PowerShell@2
    displayName: "Installing dependencies + Making build files"
    inputs:
     filePath: 'build-deps.ps1'
     arguments: 'Release'
     workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: MSBuild@1
    displayName: "Compiling project"
    inputs:
      solution: 'build/ALL_BUILD.vcxproj'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Release'
      maximumCpuCount: true
      createLogFile: true

  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: 'build/Release/'
      ArtifactName: 'windows-x64'
      publishLocation: 'Container'

- job: "Windows_x86"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: Cache@2
    inputs:
      key: 'v1-x86 | vcpkg | "$(Agent.OS)" | "C:\vcpkg\.git\HEAD"'
      restoreKeys: |
        v1-x86 | vcpkg | "$(Agent.OS)"
        vcpkg | "$(Agent.OS)"
        vcpkg
      path: 'C:\vcpkg'
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Cache vcpkg

  - task: PowerShell@2
    displayName: "Installing dependencies + Making build files"
    inputs:
     filePath: 'build-deps-ci-x86.ps1'
     arguments: 'Release true'
     workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: MSBuild@1
    displayName: "Compiling project"
    inputs:
      solution: 'build-win32/ALL_BUILD.vcxproj'
      msbuildArchitecture: 'x86'
      platform: 'Win32'
      configuration: 'Release'
      maximumCpuCount: true
      createLogFile: true

  - task: PublishBuildArtifacts@1
    displayName: "Publishing build artifacts"
    inputs:
      PathtoPublish: 'build-win32/Release/'
      ArtifactName: 'windows-x86'
      publishLocation: 'Container'

- job: Ubuntu
  pool:
    vmImage: ubuntu-20.04
  steps:
    - task: Bash@3
      displayName: "Installing dependencies + Making build files"
      inputs:
        filePath: 'build-deps.sh'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: Bash@3
      displayName: "Building project"
      inputs:
        filePath: 'build.sh'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: "Publishing build artifacts"
      inputs:
        PathtoPublish: '/usr/local/bin/Warspite/'
        ArtifactName: 'linux'
        publishLocation: 'Container'
        
- job: Ubuntu_ARM64
  pool:
    RPi
  steps:
    - task: Bash@3
      displayName: "Installing dependencies + Making build files"
      inputs:
        filePath: 'build-deps.sh'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: Bash@3
      displayName: "Building project"
      inputs:
        filePath: 'build.sh'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: "Publishing build artifacts"
      inputs:
        PathtoPublish: '/usr/local/bin/Warspite/'
        ArtifactName: 'linux-arm64'
        publishLocation: 'Container'
